sudo: required
services:
  - docker

before_install:
  - docker build -t gashers82/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run gashers82/react-test npm run test -- --coverage

after_success:
  - docker build -t gashers82/multiple-client ./client
  - docker build -t gashers82/multiple-nginx ./nginx
  - docker build -t gashers82/multiple-server ./server
  - docker build -t gashers82/multiple-worker ./worker
  #push to Docker hub (docker login)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push gashers82/multiple-client
  - docker push gashers82/multiple-nginx
  - docker push gashers82/multiple-server
  - docker push gashers82/multiple-worker

